version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes: 
      - ./.db:/var/lib/postgresql/data