version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '54321:5432'
    volumes: 
      - ./.db/data:/var/lib/postgresql/data
  adminer:
      image: michalhosna/adminer
      ports:
          - 8080:8080
      environment:
          ADMINER_DB: chat
          ADMINER_DRIVER: pgsql
          ADMINER_PASSWORD: admin
          ADMINER_SERVER: db
          ADMINER_USERNAME: admin
          ADMINER_AUTOLOGIN: 1
          ADMINER_NAME: Adminer
  adminer-remote:
      image: michalhosna/adminer
      ports:
          - 8081:8080
      environment:
          ADMINER_DB: chat # TODO: Get from env_file
          ADMINER_DRIVER: pgsql
          ADMINER_PASSWORD: admin
          ADMINER_SERVER: db
          ADMINER_USERNAME: admin
          ADMINER_AUTOLOGIN: 1
          ADMINER_NAME: Adminer